# version: "3.8"

# services:
#   db:
#     image: postgres:13-alpine
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: BenCuber@2601
#       POSTGRES_DB: badminton
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   web:
#     build: .
#     command: ["python", "app.py"]
#     volumes:
#       - .:/app
#     ports:
#       - "5000:5000"
#     environment:
#       FLASK_ENV: development
#       DATABASE_URL: postgresql://postgres:BenCuber%402601@localhost/badminton
#     depends_on:
#       - db

# volumes:
#   postgres_data:
version: "3.8"

services:
  app:
    image: learning-docker/python:v1
    ports:
      - "5000:5000"
    restart: unless-stopped
