"""Reinitialize migrations

Revision ID: 09a5b9b7aa92
Revises: 
Create Date: 2024-11-16 15:29:44.200214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09a5b9b7aa92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['branch_id'])
        batch_op.drop_column('branch_name')

    with op.batch_alter_table('rackets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('stiffness', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('max_tension', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('technology', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.Enum('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sales', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('available_location', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('Length')
        batch_op.drop_column('MaxTension')
        batch_op.drop_column('Brand')
        batch_op.drop_column('AvailableLocation')
        batch_op.drop_column('Price')
        batch_op.drop_column('ProductID')
        batch_op.drop_column('Balance')
        batch_op.drop_column('Stock')
        batch_op.drop_column('ProductName')
        batch_op.drop_column('Technology')
        batch_op.drop_column('Line')
        batch_op.drop_column('Weight')
        batch_op.drop_column('Description')
        batch_op.drop_column('Sales')
        batch_op.drop_column('Status')
        batch_op.drop_column('ImageUrl')
        batch_op.drop_column('Stiffness')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('size', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('available_size', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('technology', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.Enum('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sales', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('available_location', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('Brand')
        batch_op.drop_column('Color')
        batch_op.drop_column('Price')
        batch_op.drop_column('Size')
        batch_op.drop_column('Technology')
        batch_op.drop_column('ProductID')
        batch_op.drop_column('ProductName')
        batch_op.drop_column('Stock')
        batch_op.drop_column('Description')
        batch_op.drop_column('Sales')
        batch_op.drop_column('Status')
        batch_op.drop_column('ImageUrl')
        batch_op.drop_column('AvailableLocation')
        batch_op.drop_column('AvailableSize')

    with op.batch_alter_table('shuttlecocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuttle_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('no_per_tube', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.Enum('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sales', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('available_location', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('Brand')
        batch_op.drop_column('Price')
        batch_op.drop_column('ProductID')
        batch_op.drop_column('Stock')
        batch_op.drop_column('ProductName')
        batch_op.drop_column('ShuttleType')
        batch_op.drop_column('Speed')
        batch_op.drop_column('Description')
        batch_op.drop_column('Status')
        batch_op.drop_column('Sales')
        batch_op.drop_column('ImageUrl')
        batch_op.drop_column('AvailableLocation')
        batch_op.drop_column('NoPerTube')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shuttlecocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NoPerTube', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('AvailableLocation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ImageUrl', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Sales', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Speed', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ShuttleType', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProductName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProductID', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Brand', postgresql.ENUM('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), autoincrement=False, nullable=False))
        batch_op.drop_column('available_location')
        batch_op.drop_column('stock')
        batch_op.drop_column('sales')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('brand')
        batch_op.drop_column('product_name')
        batch_op.drop_column('image_url')
        batch_op.drop_column('product_id')
        batch_op.drop_column('no_per_tube')
        batch_op.drop_column('speed')
        batch_op.drop_column('shuttle_type')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AvailableSize', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('AvailableLocation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ImageUrl', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Sales', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProductName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProductID', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Technology', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Size', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Color', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Brand', postgresql.ENUM('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), autoincrement=False, nullable=False))
        batch_op.drop_column('available_location')
        batch_op.drop_column('stock')
        batch_op.drop_column('sales')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('brand')
        batch_op.drop_column('product_name')
        batch_op.drop_column('image_url')
        batch_op.drop_column('product_id')
        batch_op.drop_column('technology')
        batch_op.drop_column('available_size')
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    with op.batch_alter_table('rackets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Stiffness', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ImageUrl', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Sales', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Weight', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Line', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Technology', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ProductName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Balance', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ProductID', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('AvailableLocation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Brand', postgresql.ENUM('LINING', 'YONEX', 'VICTOR', 'MIZUNO', 'VS', 'KUMPOO', 'APACS', 'PROACE', 'FLEET', 'FLYPOWER', 'RESON', name='brand'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('MaxTension', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Length', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('available_location')
        batch_op.drop_column('stock')
        batch_op.drop_column('sales')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('brand')
        batch_op.drop_column('product_name')
        batch_op.drop_column('image_url')
        batch_op.drop_column('product_id')
        batch_op.drop_column('technology')
        batch_op.drop_column('length')
        batch_op.drop_column('max_tension')
        batch_op.drop_column('balance')
        batch_op.drop_column('weight')
        batch_op.drop_column('stiffness')
        batch_op.drop_column('line')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('users',
    sa.Column('UserID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mail', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Phonenumber', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserID', name='users_pkey'),
    sa.UniqueConstraint('mail', name='users_mail_key')
    )
    # ### end Alembic commands ###
